### ISSUE TITLE
When use popup-imenu and input Pattern,  it cannot jump to the definition of pattern

### ISSUE THREAD

**Issue by triyes** [ancane/popup-imenu#10]
It cannot jump to the definition of pattern. It raises an error as follow:
let*: Wrong type argument: integer-or-marker-p, #<overlay from 2576 to 2602 in server.c>

Emacs version: 25.1.1

popup-imenu configure:
;;popup-imenu
;;M-x popup-imenu
(add-to-list 'load-path (concat plugins "popup-imenu"))
(require 'popup-imenu)
(setq popup-imenu-position 'point)
(setq popup-imenu-style 'indent)
(global-set-key (kbd "C-p") 'popup-imenu)
(define-key popup-isearch-keymap (kbd "C-p") 'popup-isearch-cancel)

**Comment by ancane** [comment]
Hey. Thanks for reporting. Could you please, tell what major-mode was it? And maybe give me a sample buffer text, at which popup was failing? Thanks.

**Comment by triyes** [comment]
The major-mode is C/l mode(editing C code). Every input for popup-imenu will encounter the same error. Thanks.
The sample buffer text:
![popup-imenu](https://cloud.githubusercontent.com/assets/4339678/24301679/2355686e-10a8-11e7-9f7d-efbb39eb56f7.png)

**Comment by ancane** [comment]
Cool, thanks. Will try to figure it out over the weekend.

**Comment by ancane** [comment]
@triyes Trying to catch that error... no luck so far. Could you also post any extra setup you got for imenu in C/l mode, please? And it would be great if you could check if jumping via regular M-x `imenu` works for you? Thanks.

**Comment by ancane** [comment]
Popup-imenu had issue handling semantic-imenu index. Should be ok now.
