### ISSUE TITLE
Unrecognised keyword argument :isearch-filter to popup-imenu*

### ISSUE THREAD

**Issue by Araeos** [ancane/popup-imenu#11]
`M-x popup-imenu` stops with the message:

> popup-menu*: Keyword argument :isearch-filter not one of (:point :around :width :height :max-width :margin :margin-left :margin-right :scroll-bar :symbol :parent :parent-offset :cursor :keymap :fallback :help-delay :nowait :prompt :isearch :isearch-cursor-color :isearch-keymap :isearch-callback :initial-index)

In [this gist](https://gist.github.com/Araeos/2ac09ff2cfa18fdaf8157a4bf6c33cbe) is a edebug trace with the `:isearch-filter` parameter shown before the error is detected.

**Comment by ancane** [comment]
Hi, @Araeos.
popup-imenu depends on popup.el version 0.5.3. [isearch-filter](https://github.com/auto-complete/popup-el/blob/v0.5.3/popup.el#L1315) became available since then. Updating popup.el to 0.5.3 should help.

**Comment by Araeos** [comment]
Yes, thank you. I forget to upgrade my installed packages. I am now using the melpa version 20160709.729 of popup and it works correctly now.
