### ISSUE TITLE
Animated gif?

### ISSUE THREAD

**Issue by fommil** [ancane/popup-imenu#4]
Would be nice to show what it can do

**Comment by fommil** [comment]
![popup-imenu](https://cloud.githubusercontent.com/assets/1914041/12019024/0779eac4-ad63-11e5-8b5a-0bd323d4e111.gif)

**Comment by ancane** [comment]
I made a gif, showing popup-imenu from markdown, haskel, elisp and gnu make modes. Is it good enough?

**Comment by fommil** [comment]
ok! Although you may have missed my one (above)

**Comment by ancane** [comment]
Oh, sorry. Thought it was an example and wanted to show more then one mode.
