### ISSUE TITLE
hierarchy view?

### ISSUE THREAD

**Issue by fommil** [ancane/popup-imenu#9]
When editing org-mode or Markdown files (e.g. the ensime documentation) it would be really good if popup-imenu showed different levels in a hierarchy, like a table of contents.

**Comment by ancane** [comment]
Thanks, I see the idea. 
Well, at the moment, imenu items are just linearized into plane list, discarding item hierarchy, if any. I can think of 2 hierarchy-view options: item indentation, and popup.el [cascade menus](https://raw.githubusercontent.com/auto-complete/popup-el/master/etc/images/popup3.png). Will make it configurable.

**Comment by fommil** [comment]
btw we added popup-imenu to the emacs hacks list on http://ensime.github.io/editors/emacs/hacks/#popup-summary

**Comment by ancane** [comment]
How cool is that! Thank you.

**Comment by ancane** [comment]
v0.4 is capable of displaying indented imenus. But there is an interesting side effect: spaces take part in flx match. As for cascade-menus - I have no idea how to apply flx here. Gave up on it for now.
